version: '3'

services:
  apache:
    image: php:8.0-apache
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_de_dados

#  api:
#    build:
#      context: "./"
#      dockerfile: Dockerfile